# Book settings
# Learn more at https://jupyterbook.org/customize/config.html
#
title: Mathematica para matemáticos (WIP)
author: Rodrigo Girão Serrão
logo: logo.png

execute:
    execute_notebooks: cache

html:
  extra_footer: "Se gostaste do livro e/ou se te está a ajudar, considera <a href='github.com/RojerGS/mpm'>marcar o repositório no GitHub</a> com uma estrela."
  google_analytics_id: "G-3S8EVP8J56"
  home_page_in_navbar: false
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

latex:
  latex_documents:
    targetname: mpm.tex

parse:
  myst_extended_syntax: true

repository:
  branch: main
  url: https://github.com/RojerGS/mpm

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
